name: micro_ci
description: CI at home.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  collection: ^1.18.0
  dart_mappable: ^3.2.0
  dotenv: ^4.1.0
  glob: ^2.1.2
  http: ^1.1.0
  path: ^1.8.3
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  watcher: ^1.1.0
  yaml: ^3.1.3
  zekfad_lints: ^1.2.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^3.2.1
  lints: ^2.0.0

dependency_overrides:
  yaml:
    git: https://github.com/Zekfad/yaml.git
